### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by rparini** [rparini/cxroots#155]
Would be helpful for Pylance to have type hints on functions. Could also run mypy/pyright/pytype in a github action to verify types

Will probably go with Pyright because I use that at work and it has good integration with VSCode via pylance.

**Comment by rparini** [comment]
Just ran mypy, pyright and pytype on the current, almost entirely untyped, codebase.

[Pytype](https://github.com/google/pytype) reports a potential error in paths.py but then stops, unable to make any more progress.
```
rparini@MacBook-Air cxroots % pytype cxroots -k
...
File "/Users/rparini/Documents/Repositories/cxroots/cxroots/paths.py", line 202, in integrand: No attribute 'dzdt' on ComplexPath [attribute-error]
...
ninja: build stopped: cannot make progress due to previous errors.
```

[Pyright](https://github.com/microsoft/pyright) reports the same paths.py error but also a lot more
```
/Users/rparini/Documents/Repositories/cxroots/cxroots/contour.py
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contour.py:162:30 - error: Cannot access member "_created_by_subdivision_axis" for type "Contour"
    Member "_created_by_subdivision_axis" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contour.py:162:75 - error: Cannot access member "axis_name" for type "Contour"
    Member "axis_name" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contour.py:167:24 - error: Cannot access member "subdivide" for type "Contour"
    Member "subdivide" is unknown (reportGeneralTypeIssues)
/Users/rparini/Documents/Repositories/cxroots/cxroots/paths.py
  /Users/rparini/Documents/Repositories/cxroots/cxroots/paths.py:197:30 - error: Cannot access member "_reversePath" for type "ComplexPath"
    Member "_reversePath" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/paths.py:195:61 - error: Cannot access member "_reversePath" for type "ComplexPath"
    Member "_reversePath" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/paths.py:202:42 - error: Cannot access member "dzdt" for type "ComplexPath"
    Member "dzdt" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/paths.py:298:14 - error: Operator "-" not supported for types "NDArray[Unknown]" and "NDArray[Unknown]" (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/paths.py:298:25 - error: Operator "-" not supported for types "NDArray[Unknown]" and "NDArray[Unknown]" (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/paths.py:298:39 - error: Operator "-" not supported for types "NDArray[Unknown]" and "NDArray[Unknown]" (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/paths.py:298:50 - error: Operator "-" not supported for types "NDArray[Unknown]" and "NDArray[Unknown]" (reportGeneralTypeIssues)
/Users/rparini/Documents/Repositories/cxroots/cxroots/root_approximation.py
  /Users/rparini/Documents/Repositories/cxroots/cxroots/root_approximation.py:183:30 - error: Argument of type "NDArray[Any]" cannot be assigned to parameter "__object" of type "list[Unknown]" in function "append"
    "NDArray[Any]" is incompatible with "list[Unknown]" (reportGeneralTypeIssues)
/Users/rparini/Documents/Repositories/cxroots/cxroots/root_finding.py
  /Users/rparini/Documents/Repositories/cxroots/cxroots/root_finding.py:275:37 - error: "subcontours" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/root_finding.py:280:50 - error: "subcontours" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/root_finding.py:457:24 - error: Expression of type "None" cannot be assigned to declared type "(integral: Unknown, err: Unknown, num_div: Unknown) -> None"
    Type "None" cannot be assigned to type "(integral: Unknown, err: Unknown, num_div: Unknown) -> None" (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/root_finding.py:614:17 - error: "progress" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/root_finding.py:615:21 - error: "task" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/root_finding.py:619:13 - error: "progress" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/root_finding.py:621:23 - error: "roots" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/root_finding.py:621:30 - error: "multiplicities" is possibly unbound (reportUnboundVariable)
/Users/rparini/Documents/Repositories/cxroots/cxroots/root_finding_demo.py
  /Users/rparini/Documents/Repositories/cxroots/cxroots/root_finding_demo.py:99:9 - error: "anim" is possibly unbound (reportUnboundVariable)
/Users/rparini/Documents/Repositories/cxroots/cxroots/root_result.py
  /Users/rparini/Documents/Repositories/cxroots/cxroots/root_result.py:24:13 - error: Cannot assign member "original_contour" for type "RootResult"
    Member "original_contour" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/root_result.py:52:14 - error: Cannot access member "original_contour" for type "RootResult"
    Member "original_contour" is unknown (reportGeneralTypeIssues)
/Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py:91:18 - error: Cannot assign member "_created_by_subdivision_axis" for type "Annulus"
    Member "_created_by_subdivision_axis" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py:92:18 - error: Cannot assign member "_created_by_subdivision_axis" for type "Annulus"
    Member "_created_by_subdivision_axis" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py:111:21 - error: "box1" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py:111:27 - error: "box2" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py:112:17 - error: Cannot assign member "_created_by_subdivision_axis" for type "Annulus"
    Member "_created_by_subdivision_axis" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py:112:17 - error: Cannot assign member "_created_by_subdivision_axis" for type "AnnulusSector"
    Member "_created_by_subdivision_axis" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py:113:17 - error: Cannot assign member "_parentBox" for type "Annulus"
    Member "_parentBox" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py:113:17 - error: Cannot assign member "_parentBox" for type "AnnulusSector"
    Member "_parentBox" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py:114:29 - error: "box1" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py:114:35 - error: "box2" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py:116:16 - error: "box1" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus.py:116:22 - error: "box2" is possibly unbound (reportUnboundVariable)
/Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus_sector.py
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus_sector.py:161:21 - error: "box1" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus_sector.py:161:27 - error: "box2" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus_sector.py:162:17 - error: Cannot assign member "_created_by_subdivision_axis" for type "AnnulusSector"
    Member "_created_by_subdivision_axis" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus_sector.py:163:17 - error: Cannot assign member "_parentBox" for type "AnnulusSector"
    Member "_parentBox" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus_sector.py:164:29 - error: "box1" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus_sector.py:164:35 - error: "box2" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus_sector.py:166:16 - error: "box1" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/annulus_sector.py:166:22 - error: "box2" is possibly unbound (reportUnboundVariable)
/Users/rparini/Documents/Repositories/cxroots/cxroots/contours/circle.py
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/circle.py:77:27 - error: Argument of type "str" cannot be assigned to parameter "__i" of type "SupportsIndex | slice" in function "__getitem__"
    Type "str" cannot be assigned to type "SupportsIndex | slice"
      "str" is incompatible with protocol "SupportsIndex"
        "__index__" is not present
      "str" is incompatible with "slice" (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/circle.py:84:21 - error: "box1" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/circle.py:84:27 - error: "box2" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/circle.py:87:33 - error: "box1" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/circle.py:87:39 - error: "box2" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/circle.py:89:16 - error: "box1" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/circle.py:89:22 - error: "box2" is possibly unbound (reportUnboundVariable)
/Users/rparini/Documents/Repositories/cxroots/cxroots/contours/rectangle.py
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/rectangle.py:128:21 - error: "box1" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/rectangle.py:128:27 - error: "box2" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/rectangle.py:129:17 - error: Cannot assign member "_created_by_subdivision_axis" for type "Rectangle"
    Member "_created_by_subdivision_axis" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/rectangle.py:130:17 - error: Cannot assign member "_parentBox" for type "Rectangle"
    Member "_parentBox" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/rectangle.py:131:29 - error: "box1" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/rectangle.py:131:35 - error: "box2" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/rectangle.py:133:16 - error: "box1" is possibly unbound (reportUnboundVariable)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/contours/rectangle.py:133:22 - error: "box2" is possibly unbound (reportUnboundVariable)
/Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_countroots.py
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_countroots.py:32:14 - error: Expression of type "None" cannot be assigned to declared type "(z: Unknown) -> Unknown"
    Type "None" cannot be assigned to type "(z: Unknown) -> Unknown" (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_countroots.py:89:16 - error: Cannot access member "count_enclosed_roots" for type "Rectangle"
    Member "count_enclosed_roots" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_countroots.py:90:16 - error: Cannot access member "count_enclosed_roots" for type "Rectangle"
    Member "count_enclosed_roots" is unknown (reportGeneralTypeIssues)
/Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:26:18 - error: Cannot access member "C" for type "RootfindingTests"
    Member "C" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:26:31 - error: Cannot access member "f" for type "RootfindingTests"
    Member "f" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:26:39 - error: Cannot access member "df" for type "RootfindingTests"
    Member "df" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:27:19 - error: Cannot access member "roots" for type "RootfindingTests"
    Member "roots" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:27:31 - error: Cannot access member "multiplicities" for type "RootfindingTests"
    Member "multiplicities" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:33:18 - error: Cannot access member "C" for type "RootfindingTests"
    Member "C" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:33:31 - error: Cannot access member "f" for type "RootfindingTests"
    Member "f" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:34:19 - error: Cannot access member "roots" for type "RootfindingTests"
    Member "roots" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:34:31 - error: Cannot access member "multiplicities" for type "RootfindingTests"
    Member "multiplicities" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:40:18 - error: Cannot access member "C" for type "RootfindingTests"
    Member "C" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:40:31 - error: Cannot access member "f" for type "RootfindingTests"
    Member "f" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:40:39 - error: Cannot access member "df" for type "RootfindingTests"
    Member "df" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:41:19 - error: Cannot access member "roots" for type "RootfindingTests"
    Member "roots" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:41:31 - error: Cannot access member "multiplicities" for type "RootfindingTests"
    Member "multiplicities" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:47:18 - error: Cannot access member "C" for type "RootfindingTests"
    Member "C" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:47:31 - error: Cannot access member "f" for type "RootfindingTests"
    Member "f" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:48:19 - error: Cannot access member "roots" for type "RootfindingTests"
    Member "roots" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:48:31 - error: Cannot access member "multiplicities" for type "RootfindingTests"
    Member "multiplicities" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:56:39 - error: Cannot access member "roots" for type "MultiplicityTests"
    Member "roots" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:57:49 - error: Cannot access member "f" for type "MultiplicityTests"
    Member "f" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:57:69 - error: Cannot access member "multiplicities" for type "MultiplicityTests"
    Member "multiplicities" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:61:39 - error: Cannot access member "roots" for type "MultiplicityTests"
    Member "roots" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:62:49 - error: Cannot access member "f" for type "MultiplicityTests"
    Member "f" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:62:60 - error: Cannot access member "df" for type "MultiplicityTests"
    Member "df" is unknown (reportGeneralTypeIssues)
  /Users/rparini/Documents/Repositories/cxroots/cxroots/tests/test_rootfinding.py:62:72 - error: Cannot access member "multiplicities" for type "MultiplicityTests"
    Member "multiplicities" is unknown (reportGeneralTypeIssues)
```
Some of these are maybe not "real" issues but more potentially bad practice, like setting accessing some attributes like `_created_by_subdivision_axis` that are not defined in the class's init. Would be interesting to see how this compares to pytype as the errors reported by that are worked through.

mypy reports nothing. I guess it really needs type annotations to do anything useful.
```
rparini@MacBook-Air cxroots % mypy cxroots
cxroots/util.py:2: error: Skipping analyzing "scipy.integrate": module is installed, but missing library stubs or py.typed marker
cxroots/util.py:2: error: Skipping analyzing "scipy": module is installed, but missing library stubs or py.typed marker
cxroots/util.py:3: error: Skipping analyzing "numpydoc.docscrape": module is installed, but missing library stubs or py.typed marker
cxroots/root_result.py:50: error: Skipping analyzing "matplotlib.pyplot": module is installed, but missing library stubs or py.typed marker
cxroots/root_result.py:50: error: Skipping analyzing "matplotlib": module is installed, but missing library stubs or py.typed marker
cxroots/iterative_methods.py:134: error: Skipping analyzing "mpmath": module is installed, but missing library stubs or py.typed marker
cxroots/iterative_methods.py:135: error: Skipping analyzing "mpmath.calculus.optimization": module is installed, but missing library stubs or py.typed marker
cxroots/root_counting.py:5: error: Skipping analyzing "numdifftools": module is installed, but missing library stubs or py.typed marker
cxroots/root_counting.py:7: error: Skipping analyzing "scipy.integrate": module is installed, but missing library stubs or py.typed marker
cxroots/root_counting.py:7: error: Skipping analyzing "scipy": module is installed, but missing library stubs or py.typed marker
cxroots/paths.py:6: error: Skipping analyzing "scipy.integrate": module is installed, but missing library stubs or py.typed marker
cxroots/paths.py:6: error: Skipping analyzing "scipy": module is installed, but missing library stubs or py.typed marker
cxroots/paths.py:111: error: Skipping analyzing "matplotlib.pyplot": module is installed, but missing library stubs or py.typed marker
cxroots/paths.py:111: error: Skipping analyzing "matplotlib": module is installed, but missing library stubs or py.typed marker
cxroots/root_approximation.py:5: error: Skipping analyzing "scipy.linalg": module is installed, but missing library stubs or py.typed marker
cxroots/root_approximation.py:5: error: Skipping analyzing "scipy": module is installed, but missing library stubs or py.typed marker
cxroots/root_finding.py:6: error: Skipping analyzing "numpydoc.docscrape": module is installed, but missing library stubs or py.typed marker
cxroots/root_finding_demo.py:7: error: Skipping analyzing "matplotlib.pyplot": module is installed, but missing library stubs or py.typed marker
cxroots/root_finding_demo.py:7: error: Skipping analyzing "matplotlib": module is installed, but missing library stubs or py.typed marker
cxroots/contour.py:103: error: Skipping analyzing "matplotlib.pyplot": module is installed, but missing library stubs or py.typed marker
cxroots/contour.py:103: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
cxroots/contour.py:103: error: Skipping analyzing "matplotlib": module is installed, but missing library stubs or py.typed marker
cxroots/derivative.py:6: error: Skipping analyzing "numdifftools.fornberg": module is installed, but missing library stubs or py.typed marker
cxroots/derivative.py:6: error: Skipping analyzing "numdifftools": module is installed, but missing library stubs or py.typed marker
Found 23 errors in 10 files (checked 31 source files)
```
